import type { KPISection, KPIUnit, KPIDirection } from './types';

export interface KPIThresholds {
  /** Pro down_good: hodnota ≤ green je zelená. Pro up_good: ≥ green. */
  green: number;
  acceptable: number;
  red: number;
}

export interface KPIDefinition {
  id: string;
  nameCs: string;
  descriptionCs: string;
  section: KPISection;
  priority: 1 | 2 | 3;
  owner: string;
  frequency: 'monthly' | 'quarterly' | 'semi-annual' | 'annual';
  formula: string;
  direction: KPIDirection;
  target: number | null;
  thresholds: KPIThresholds;
  unit: KPIUnit;
  actionIfOffTrack: string;
  tags: string[];
}

export const KPI_CATALOG: KPIDefinition[] = [
  // ─── Sekce I: HR Statistics ─────────────────────────────────────
  {
    id: 'headcount',
    nameCs: 'Celkový počet zaměstnanců (HC)',
    descriptionCs: 'Aktivní zaměstnanci (HPP + DPP + DPČ) k poslednímu dni období.',
    section: 'I',
    priority: 1,
    owner: 'HR Reporting',
    frequency: 'monthly',
    formula: 'count(employees where terminationDate IS NULL OR terminationDate > period_end)',
    direction: 'flat_good',
    target: 1735,
    thresholds: { green: 0.05, acceptable: 0.10, red: 0.15 }, // odchylka od targetu
    unit: 'count',
    actionIfOffTrack: 'Analyzovat příčinu odchylky od plánu HC. Spustit nábor nebo zastavit hiring dle směru odchylky.',
    tags: ['P1', 'core', 'headcount'],
  },
  {
    id: 'fte_ratio',
    nameCs: 'FTE / HC poměr',
    descriptionCs: 'Průměrný FTE na zaměstnance — indikátor plnoúvazkového pokrytí.',
    section: 'I',
    priority: 2,
    owner: 'HR Reporting',
    frequency: 'monthly',
    formula: 'sum(fte) / count(active_employees)',
    direction: 'up_good',
    target: 0.9,
    thresholds: { green: 0.85, acceptable: 0.75, red: 0.65 },
    unit: 'ratio',
    actionIfOffTrack: 'Přezkoumat podíl zkrácených úvazků. Zvýšit nabídku HPP na klíčových pozicích.',
    tags: ['core', 'workforce'],
  },
  {
    id: 'gender_pay_gap',
    nameCs: 'Gender pay gap',
    descriptionCs: 'Procentní rozdíl průměrné hrubé mzdy mužů a žen (mean gap, raw).',
    section: 'I',
    priority: 1,
    owner: 'HR Reporting',
    frequency: 'annual',
    formula: '(avg_male_salary - avg_female_salary) / avg_male_salary * 100',
    direction: 'down_good',
    target: 0,
    thresholds: { green: 5, acceptable: 12, red: 20 },
    unit: 'percent',
    actionIfOffTrack: 'Provést analýzu příčin gap (role-mix vs. přímá diskriminace). Nastartovat program spravedlivého odměňování.',
    tags: ['P1', 'DEI', 'ESG', 'compensation'],
  },
  {
    id: 'women_in_management',
    nameCs: 'Podíl žen v managementu (B0–B3)',
    descriptionCs: '% žen na manažerských pozicích (grade B0–B3).',
    section: 'I',
    priority: 2,
    owner: 'HR Reporting',
    frequency: 'annual',
    formula: 'count(female, grade IN [B0,B1,B2,B3]) / count(all, grade IN [B0,B1,B2,B3]) * 100',
    direction: 'up_good',
    target: 35,
    thresholds: { green: 30, acceptable: 22, red: 15 },
    unit: 'percent',
    actionIfOffTrack: 'Spustit Women in Leadership program. Mentoring a targeted development pro high-potential ženy.',
    tags: ['DEI', 'ESG', 'leadership'],
  },

  // ─── Sekce II: Workforce Movement ───────────────────────────────
  {
    id: 'employees_in',
    nameCs: 'Nástupy (měsíční)',
    descriptionCs: 'Počet nově nastoupivších zaměstnanců v daném měsíci.',
    section: 'II',
    priority: 1,
    owner: 'HR Reporting',
    frequency: 'monthly',
    formula: 'count(workforce_events where type = hire AND date IN period)',
    direction: 'flat_good',
    target: null,
    thresholds: { green: 0, acceptable: 0, red: 0 }, // kontextové — dle plánu
    unit: 'count',
    actionIfOffTrack: 'Porovnat s nábor plánem. Identifikovat bottlenecky v hiring funnel.',
    tags: ['P1', 'movement', 'recruitment'],
  },
  {
    id: 'employees_out',
    nameCs: 'Odchody (měsíční)',
    descriptionCs: 'Počet zaměstnanců, kteří ukončili pracovní poměr v daném měsíci.',
    section: 'II',
    priority: 1,
    owner: 'HR Reporting',
    frequency: 'monthly',
    formula: 'count(workforce_events where type = terminate AND date IN period)',
    direction: 'down_good',
    target: null,
    thresholds: { green: 0, acceptable: 0, red: 0 },
    unit: 'count',
    actionIfOffTrack: 'Analyzovat důvody odchodů. Spustit exit interview analýzu.',
    tags: ['P1', 'movement', 'retention'],
  },
  {
    id: 'untaken_holiday',
    nameCs: 'Nevybraná dovolená (průměr dní)',
    descriptionCs: 'Průměrný zůstatek nevybrané dovolené na aktivního zaměstnance.',
    section: 'II',
    priority: 1,
    owner: 'Payroll',
    frequency: 'monthly',
    formula: 'sum(vacation_days - taken_vacation_days) / headcount',
    direction: 'down_good',
    target: 3,
    thresholds: { green: 5, acceptable: 10, red: 15 },
    unit: 'days',
    actionIfOffTrack: 'Aktivní komunikace zaměstnancům o nevybrané dovolené. Nastavit plán čerpání.',
    tags: ['P1', 'absence', 'wellbeing'],
  },
  {
    id: 'sickness_rate',
    nameCs: 'Nemocnost',
    descriptionCs: '% pracovních dní ztracených nemocí z celkového fondu pracovního času.',
    section: 'II',
    priority: 2,
    owner: 'Payroll',
    frequency: 'monthly',
    formula: 'sum(sick_days) / (headcount * working_days_in_period) * 100',
    direction: 'down_good',
    target: 2,
    thresholds: { green: 3, acceptable: 5, red: 7 },
    unit: 'percent',
    actionIfOffTrack: 'Identifikovat divize s nejvyšší nemocností. Spustit wellbeing a preventivní program.',
    tags: ['absence', 'wellbeing', 'ESG'],
  },

  // ─── Sekce III: Cost & Structure ────────────────────────────────
  {
    id: 'avg_wage',
    nameCs: 'Průměrná hrubá mzda (Kč/měs.)',
    descriptionCs: 'Průměrná měsíční hrubá základní mzda aktivního zaměstnance (HPP).',
    section: 'III',
    priority: 1,
    owner: 'Payroll',
    frequency: 'monthly',
    formula: 'sum(baseSalary) / count(active_PP_employees)',
    direction: 'up_good',
    target: 42000,
    thresholds: { green: 38000, acceptable: 34000, red: 30000 },
    unit: 'czk',
    actionIfOffTrack: 'Přezkoumat mzdovou politiku a trh. Připravit návrh korekcí pro HR Director.',
    tags: ['P1', 'compensation', 'core'],
  },
  {
    id: 'wage_kpi',
    nameCs: 'Wage KPI (mzdové náklady vs. plán)',
    descriptionCs: 'Skutečné mzdové náklady jako % plánovaných mzdových nákladů.',
    section: 'III',
    priority: 2,
    owner: 'Payroll',
    frequency: 'monthly',
    formula: 'actual_total_wage_cost / budgeted_wage_cost * 100',
    direction: 'flat_good',
    target: 100,
    thresholds: { green: 5, acceptable: 10, red: 15 }, // % odchylka od 100
    unit: 'percent',
    actionIfOffTrack: 'Identifikovat zdroj odchylky (přečerpání vs. plán). Aktualizovat forecast pro CFO.',
    tags: ['compensation', 'budget', 'finance'],
  },
  {
    id: 'cap_kpi',
    nameCs: 'CAP KPI (plnění kapacitního plánu)',
    descriptionCs: 'Skutečný FTE jako podíl plánovaného FTE (Cap) napříč organizací.',
    section: 'III',
    priority: 2,
    owner: 'HR Reporting',
    frequency: 'monthly',
    formula: 'sum(actualFte) / sum(capFte)',
    direction: 'up_good',
    target: 0.95,
    thresholds: { green: 0.90, acceptable: 0.80, red: 0.70 },
    unit: 'ratio',
    actionIfOffTrack: 'Identifikovat divize s nejvyšší vacancy rate. Prioritizovat nábor na podplněné pozice.',
    tags: ['capacity', 'workforce', 'budget'],
  },
  {
    id: 'hc_per_division',
    nameCs: 'HC/FTE per divize vs. budget',
    descriptionCs: 'Průměrná odchylka HC od kapacitního plánu across divisions.',
    section: 'III',
    priority: 1,
    owner: 'HR Reporting',
    frequency: 'monthly',
    formula: 'avg(|actual_hc - cap_hc| / cap_hc * 100) across divisions',
    direction: 'down_good',
    target: 3,
    thresholds: { green: 5, acceptable: 10, red: 15 },
    unit: 'percent',
    actionIfOffTrack: 'Mapa odchylek per divize — přesunout nábor focus na nejvíce podplněné. Zvážit realokaci FTE.',
    tags: ['P1', 'capacity', 'workforce'],
  },

  // ─── Sekce IV: Recruitment ───────────────────────────────────────
  {
    id: 'time_to_fill',
    nameCs: 'Doba do obsazení pozice (TTF)',
    descriptionCs: 'Průměrná doba od publikace inzerátu do nástupu kandidáta (kalendářní dny).',
    section: 'IV',
    priority: 2,
    owner: 'Recruiting',
    frequency: 'monthly',
    formula: 'mean(hireDate - publishedDate) in days',
    direction: 'down_good',
    target: 25,
    thresholds: { green: 27, acceptable: 40, red: 55 },
    unit: 'days',
    actionIfOffTrack: 'Analyzovat bottlenecky ve funnel (screening / interview scheduling). Přidat kapacitu nebo zjednodušit proces.',
    tags: ['recruitment', 'efficiency'],
  },
  {
    id: 'ttf_critical',
    nameCs: 'TTF — kritické pozice',
    descriptionCs: 'Průměrná doba obsazení pouze pro pozice označené jako kritické.',
    section: 'IV',
    priority: 2,
    owner: 'Recruiting',
    frequency: 'monthly',
    formula: 'mean(hireDate - publishedDate) where critical = true',
    direction: 'down_good',
    target: 14,
    thresholds: { green: 20, acceptable: 35, red: 50 },
    unit: 'days',
    actionIfOffTrack: 'Talent pipeline pro kritické pozice. Executive search pro neobsazené klíčové role.',
    tags: ['recruitment', 'critical', 'P1'],
  },
  {
    id: 'cost_per_hire',
    nameCs: 'Náklady na nábor (CpH)',
    descriptionCs: 'Průměrné celkové náklady na obsazení jedné pozice (inzerce, agentury, interní čas).',
    section: 'IV',
    priority: 2,
    owner: 'Recruiting',
    frequency: 'annual',
    formula: 'sum(recruitment_costs) / count(hires)',
    direction: 'down_good',
    target: 22000,
    thresholds: { green: 25000, acceptable: 35000, red: 50000 },
    unit: 'czk',
    actionIfOffTrack: 'Optimalizovat mix zdrojů (interní doporučení vs. agentury). Zvýšit podíl AAA Career.',
    tags: ['recruitment', 'cost', 'efficiency'],
  },
  {
    id: 'quality_of_hire',
    nameCs: 'Kvalita náboru (early attrition)',
    descriptionCs: '% zaměstnanců, kteří odešli do 3 měsíců od nástupu (early attrition).',
    section: 'IV',
    priority: 2,
    owner: 'Recruiting',
    frequency: 'quarterly',
    formula: 'count(terminated in 90 days of hire) / count(hires in period) * 100',
    direction: 'down_good',
    target: 5,
    thresholds: { green: 8, acceptable: 15, red: 25 },
    unit: 'percent',
    actionIfOffTrack: 'Přezkoumat selekční kritéria a onboarding program. Exit interview s odcházejícími v prvních 3 měsících.',
    tags: ['recruitment', 'quality', 'retention'],
  },
  {
    id: 'employer_evaluation',
    nameCs: 'Hodnocení zaměstnavatele',
    descriptionCs: 'Průměrné hodnocení firmy kandidáty (škála 1–5) z recruitment procesu.',
    section: 'IV',
    priority: 2,
    owner: 'Recruiting',
    frequency: 'monthly',
    formula: 'mean(rating) from recruitment rows where rating IS NOT NULL',
    direction: 'up_good',
    target: 4.5,
    thresholds: { green: 4.0, acceptable: 3.5, red: 3.0 },
    unit: 'score',
    actionIfOffTrack: 'Přezkoumat candidate experience. Zaměřit se na komunikaci a feedback.',
    tags: ['recruitment', 'employer_brand'],
  },

  // ─── Sekce V: Retention ──────────────────────────────────────────
  {
    id: 'fluctuation_rate',
    nameCs: 'Fluktuace celková (rolling 12M)',
    descriptionCs: 'Počet dobrovolných odchodů za posledních 12 měsíců / průměrný HC × 100.',
    section: 'V',
    priority: 1,
    owner: 'HR Reporting',
    frequency: 'monthly',
    formula: 'count(voluntary terminations in 12M) / avg(monthly_hc) * 100',
    direction: 'down_good',
    target: 12,
    thresholds: { green: 15, acceptable: 22, red: 30 },
    unit: 'percent',
    actionIfOffTrack: 'Exit interview analýza. Stay interview s rizikovými segmenty. Přezkoumat odměňování vs. trh.',
    tags: ['P1', 'retention', 'core'],
  },
  {
    id: 'fluctuation_critical',
    nameCs: 'Fluktuace — kritické pozice',
    descriptionCs: 'Fluktuace pouze na pozicích označených jako kritické.',
    section: 'V',
    priority: 1,
    owner: 'HR Reporting',
    frequency: 'monthly',
    formula: 'count(terminations, critical positions, 12M) / avg(critical_hc) * 100',
    direction: 'down_good',
    target: 5,
    thresholds: { green: 8, acceptable: 15, red: 25 },
    unit: 'percent',
    actionIfOffTrack: 'Urgentní retention balíčky pro kritické role. 1:1 s přímými nadřízenými. Succession review.',
    tags: ['P1', 'retention', 'critical'],
  },

  // ─── Sekce VI: Succession ────────────────────────────────────────
  {
    id: 'succession_rate',
    nameCs: 'Míra nástupnictví (kritické pozice)',
    descriptionCs: '% kritických pozic, které mají identifikovaného nástupce (ready now nebo 1–2 roky).',
    section: 'VI',
    priority: 2,
    owner: 'Training',
    frequency: 'quarterly',
    formula: 'count(critical positions with successor) / count(critical positions) * 100',
    direction: 'up_good',
    target: 90,
    thresholds: { green: 80, acceptable: 65, red: 50 },
    unit: 'percent',
    actionIfOffTrack: 'Talent review — identifikovat kandidáty pro role bez nástupce. Spustit akcelerovaný development plán.',
    tags: ['succession', 'talent', 'risk'],
  },

  // ─── Sekce VII: Engagement ───────────────────────────────────────
  {
    id: 'enps',
    nameCs: 'eNPS (Employee Net Promoter Score)',
    descriptionCs: '(% promoterů − % detractorů) z průzkumu spokojenosti zaměstnanců.',
    section: 'VII',
    priority: 2,
    owner: 'HR Reporting',
    frequency: 'quarterly',
    formula: '(promoters - detractors) / respondents * 100',
    direction: 'up_good',
    target: 30,
    thresholds: { green: 20, acceptable: 5, red: -10 },
    unit: 'score',
    actionIfOffTrack: 'Hloubková analýza detractorů. Focus groups. Akční plán dle segmentu s nízkým eNPS.',
    tags: ['engagement', 'culture', 'ESG'],
  },

  // ─── Sekce VIII: Talent & Growth ────────────────────────────────
  {
    id: 'talent_ratio',
    nameCs: 'Podíl talent pool (high potential)',
    descriptionCs: '% zaměstnanců označených jako high potential (talentFlag = true).',
    section: 'VIII',
    priority: 3,
    owner: 'Training',
    frequency: 'annual',
    formula: 'count(talentFlag = true) / count(active_employees) * 100',
    direction: 'up_good',
    target: 18,
    thresholds: { green: 15, acceptable: 10, red: 5 },
    unit: 'percent',
    actionIfOffTrack: 'Přezkoumat kritéria talent identifikace. Rozšířit development programy.',
    tags: ['talent', 'growth', 'development'],
  },
];

export const KPI_BY_ID = new Map(KPI_CATALOG.map((k) => [k.id, k]));
