import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import seedrandom from 'seedrandom';
import { inferCriticalFlag } from '@/lib/data/heuristics/critical-position';
import { inferGrade } from '@/lib/data/heuristics/grade';
import { generateAccidents } from '@/lib/data/mock/accidents';
import { generateAbsenceForEmployee } from '@/lib/data/mock/absence';
import { generateEnpsResponses } from '@/lib/data/mock/enps';
import { generatePayrollForEmployee } from '@/lib/data/mock/payroll';
import { generatePerformanceReview } from '@/lib/data/mock/performance';
import { generateSuccessionPlan } from '@/lib/data/mock/succession';
import { generateTrainingCompletions } from '@/lib/data/mock/training';
import { createNamePseudonymizer } from '@/lib/data/parsers/names';
import { parseRecruitment } from '@/lib/data/parsers/recruitment';
import { parseStaffplan } from '@/lib/data/parsers/staffplan';
import { parseWorkforceEvents } from '@/lib/data/parsers/workforce-events';
import type {
  AbsenceRecord,
  Employee,
  Gender,
  PayrollMonth,
  PerformanceReview,
  Position,
  SuccessionPlan,
  TerminationReason,
  TrainingCompletion,
  WorkforceEvent,
  WorkAccident,
} from '@/lib/types';

const ROOT = path.resolve(__dirname, '..');
const RAW_DIR = path.join(ROOT, 'data-sources/raw');
const OUT_DIR = path.join(ROOT, 'lib/data/generated');
const SEED = 42;
const START_MONTH = '2023-01';
const END_MONTH = '2026-03';
const YEARS = [2023, 2024, 2025, 2026] as const;
const PERFORMANCE_CYCLES = ['2024', '2025'] as const;

const TERMINATION_REASONS: readonly TerminationReason[] = [
  'resignation',
  'mutual_agreement',
  'dismissal',
  'probation_end',
];

const TYPE_IMPORTS: Record<string, string> = {
  EMPLOYEES: 'Employee',
  POSITIONS: 'Position',
  DEPARTMENTS: 'Department',
  DIVISIONS: 'Division',
  PAYROLL: 'PayrollMonth',
  ABSENCE: 'AbsenceRecord',
  TRAINING: 'TrainingCompletion',
  PERFORMANCE: 'PerformanceReview',
  ENPS: 'ENPSResponse',
  ACCIDENTS: 'WorkAccident',
  SUCCESSION: 'SuccessionPlan',
  WORKFORCE_EVENTS: 'WorkforceEvent',
};

const writeTsModule = (filename: string, exportName: string, data: unknown): void => {
  const typeName = TYPE_IMPORTS[exportName];
  const importLine = typeName ? `import type { ${typeName} } from '@/lib/types';\n\n` : '';
  const typeCast = typeName ? ` as ${typeName}[]` : '';
  const jsonPayload = JSON.stringify(JSON.stringify(data));
  const body = `${importLine}// AUTO-GENERATED by scripts/gen-data.ts. DO NOT EDIT.\nexport const ${exportName} = JSON.parse(${jsonPayload})${typeCast};\n`;

  writeFileSync(path.join(OUT_DIR, filename), body, 'utf8');
};

const pick = <T>(items: readonly T[], rng: () => number): T => {
  const item = items[Math.floor(rng() * items.length)];
  if (item == null) throw new Error('Cannot pick from an empty array');
  return item;
};

const normalizeForMatch = (value: string): string =>
  value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');

const inferGenderFromName = (firstName: string, employeeId: string): Gender => {
  const normalized = normalizeForMatch(firstName);
  if (normalized.endsWith('a') || normalized.endsWith('e')) return 'female';
  const rng = seedrandom(`${SEED}:gender:${employeeId}`);
  return rng() < 0.75 ? 'male' : 'female';
};

const activeInCycle = (employee: Employee, cycle: string): boolean => {
  const year = Number(cycle);
  if (!Number.isFinite(year)) return false;
  if (new Date(employee.hireDate).getUTCFullYear() > year) return false;
  if (employee.terminationDate && new Date(employee.terminationDate).getUTCFullYear() < year) {
    return false;
  }
  return true;
};

const main = (): void => {
  console.log('HR Analytics data pipeline: start');
  mkdirSync(OUT_DIR, { recursive: true });

  const staffplan = parseStaffplan(path.join(RAW_DIR, 'Staffplan.xlsx'));
  const workforce = parseWorkforceEvents(path.join(RAW_DIR, 'Nastupy_vystupy.xlsx'));
  const recruitment = parseRecruitment(path.join(RAW_DIR, 'recruitment_report.xlsx'));

  console.log(
    `Real data parsed: ${staffplan.positions.length} positions, ${workforce.events.length} workforce events, ${recruitment.rows.length} recruitment rows`,
  );

  if (staffplan.positions.length === 0) {
    throw new Error('No staffplan positions parsed. Cannot build generated dataset.');
  }

  const deptRoleCounts = new Map<string, number>();
  for (const position of staffplan.positions) {
    const key = `${position.departmentId}:${position.roleFamily}`;
    deptRoleCounts.set(key, (deptRoleCounts.get(key) ?? 0) + 1);
  }

  const positions: Position[] = staffplan.positions.map((position) => {
    const grade = inferGrade({ title: position.title, hierCode: position.departmentId });
    const singletonInDept =
      (deptRoleCounts.get(`${position.departmentId}:${position.roleFamily}`) ?? 0) <= 2;
    const criticalFlag = inferCriticalFlag({
      grade,
      roleFamily: position.roleFamily,
      singletonInDept,
    });

    return { ...position, grade, criticalFlag };
  });

  const positionsById = new Map(positions.map((position) => [position.id, position]));
  const pseudo = createNamePseudonymizer(SEED);
  const firstPosition = positions[0];
  if (!firstPosition) throw new Error('No positions available for employee matching.');

  const matchPosition = (employeeId: string, orgUnitName: string): Position => {
    const directPositionId = staffplan.employeeToPosition.get(employeeId);
    const direct = directPositionId ? positionsById.get(directPositionId) : undefined;
    if (direct) return direct;

    const normalizedOrg = normalizeForMatch(orgUnitName);
    const byDepartment = positions.find((position) =>
      normalizedOrg.includes(normalizeForMatch(position.departmentId)),
    );
    if (byDepartment) return byDepartment;

    const byRoleFamily = positions.find((position) => {
      const roleFamily = normalizeForMatch(position.roleFamily);
      return (
        normalizedOrg.includes(roleFamily) ||
        (roleFamily === 'ops-driver' && normalizedOrg.includes('driver')) ||
        (roleFamily === 'ops-helper' && normalizedOrg.includes('helper'))
      );
    });

    return byRoleFamily ?? firstPosition;
  };

  const employees: Employee[] = [];
  for (const [employeeId, info] of workforce.employees) {
    const gender = inferGenderFromName(info.firstName, employeeId);
    const names = pseudo.pseudonymize(employeeId, gender);
    const position = matchPosition(employeeId, info.orgUnitName);
    const terminationReason = info.currentlyActive
      ? null
      : pick(TERMINATION_REASONS, seedrandom(`${SEED}:termination:${employeeId}`));
    const birthYear = 1965 + Math.floor(seedrandom(`${SEED}:birth:${employeeId}`)() * 40);

    employees.push({
      id: employeeId,
      firstName: names.firstName,
      lastName: names.lastName,
      gender,
      birthDate: `${birthYear}-06-15`,
      nationality: 'CZ',
      country: 'CZ',
      hireDate: info.firstSeenDate,
      terminationDate: info.currentlyActive ? null : info.lastSeenDate,
      terminationReason,
      positionId: position.id,
      divisionId: position.divisionId,
      departmentId: position.departmentId,
      orgUnitId: info.orgUnitCode,
      grade: position.grade,
      employmentType: info.employmentType,
      fte: Math.max(0.25, Math.min(1, position.actualFte || position.capFte || 1)),
      managerId: null,
      criticalPositionFlag: position.criticalFlag,
      talentPoolFlag: false,
      successorForPositionId: null,
    });
  }

  const payroll: PayrollMonth[] = [];
  const absence: AbsenceRecord[] = [];
  const training: TrainingCompletion[] = [];
  const performance: PerformanceReview[] = [];

  for (const employee of employees) {
    payroll.push(
      ...generatePayrollForEmployee(employee, {
        fromMonth: START_MONTH,
        toMonth: END_MONTH,
        seed: SEED,
      }),
    );

    for (const year of YEARS) {
      absence.push(...generateAbsenceForEmployee(employee, { year, seed: SEED }));
      training.push(...generateTrainingCompletions(employee, { year, seed: SEED }));
    }

    for (const cycle of PERFORMANCE_CYCLES) {
      if (activeInCycle(employee, cycle)) {
        performance.push(generatePerformanceReview(employee, { cycle, seed: SEED }));
      }
    }
  }

  const activeEmployees = employees.filter((employee) => employee.terminationDate == null);
  const enps = generateEnpsResponses(activeEmployees, {
    cycle: '2025-Q4',
    seed: SEED,
    participationRate: 0.7,
  });

  const activeHeadcountByDivision = new Map<string, number>();
  for (const employee of activeEmployees) {
    activeHeadcountByDivision.set(
      employee.divisionId,
      (activeHeadcountByDivision.get(employee.divisionId) ?? 0) + 1,
    );
  }

  const accidents: WorkAccident[] = [];
  for (const [divisionId, headcount] of activeHeadcountByDivision) {
    for (const year of YEARS) {
      accidents.push(...generateAccidents({ divisionId, year, headcount, seed: SEED }));
    }
  }

  const candidatePool = activeEmployees
    .filter((employee) => employee.grade === 'B2' || employee.grade === 'B3')
    .map((employee) => ({ employeeId: employee.id }));

  const succession: SuccessionPlan[] = positions
    .filter((position) => position.criticalFlag)
    .map((position) => {
      const incumbent = activeEmployees.find((employee) => employee.positionId === position.id);
      return generateSuccessionPlan({
        positionId: position.id,
        incumbentEmployeeId: incumbent?.id ?? null,
        candidates: candidatePool.slice(0, 25),
        seed: SEED,
      });
    });

  const workforceEvents: WorkforceEvent[] = workforce.events.map((event) => ({
    date: event.date,
    employeeId: event.employeeId,
    type: event.type,
  }));

  writeTsModule('employees.ts', 'EMPLOYEES', employees);
  writeTsModule('positions.ts', 'POSITIONS', positions);
  writeTsModule('departments.ts', 'DEPARTMENTS', staffplan.departments);
  writeTsModule('divisions.ts', 'DIVISIONS', staffplan.divisions);
  writeTsModule('payroll.ts', 'PAYROLL', payroll);
  writeTsModule('absence.ts', 'ABSENCE', absence);
  writeTsModule('training.ts', 'TRAINING', training);
  writeTsModule('performance.ts', 'PERFORMANCE', performance);
  writeTsModule('enps.ts', 'ENPS', enps);
  writeTsModule('accidents.ts', 'ACCIDENTS', accidents);
  writeTsModule('succession.ts', 'SUCCESSION', succession);
  writeTsModule('workforce-events.ts', 'WORKFORCE_EVENTS', workforceEvents);

  console.log(
    `Generated: ${employees.length} employees, ${payroll.length} payroll rows, ${absence.length} absence rows, ${training.length} training rows`,
  );
  console.log(`Done: ${OUT_DIR}`);
};

main();
