/**
 * Generuje konsolidovaný datový set:
 *   real data (staffplan + workforce events + recruitment) → kostra
 *   + heuristiky (grade, kritičnost)
 *   + mock generátory (payroll, absence, eNPS, performance, training, succession, accidents)
 *   = lib/data/generated/*.ts — import-ready TS moduly
 *
 * Spuštění: pnpm gen:data
 */
import path from 'node:path';
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import seedrandom from 'seedrandom';
import { parseStaffplan } from '@/lib/data/parsers/staffplan';
import { parseWorkforceEvents } from '@/lib/data/parsers/workforce-events';
import { parseRecruitment } from '@/lib/data/parsers/recruitment';
import { createNamePseudonymizer } from '@/lib/data/parsers/names';
import { inferGrade } from '@/lib/data/heuristics/grade';
import { inferCriticalFlag } from '@/lib/data/heuristics/critical-position';
import { generatePayrollForEmployee } from '@/lib/data/mock/payroll';
import { generateAbsenceForEmployee } from '@/lib/data/mock/absence';
import { generateEnpsResponses } from '@/lib/data/mock/enps';
import { generatePerformanceReview } from '@/lib/data/mock/performance';
import { generateTrainingCompletions } from '@/lib/data/mock/training';
import { generateSuccessionPlan } from '@/lib/data/mock/succession';
import { generateAccidents } from '@/lib/data/mock/accidents';
import type {
  Employee,
  Position,
  Gender,
  PayrollMonth,
  AbsenceRecord,
  PerformanceReview,
  ENPSResponse,
  TrainingCompletion,
  WorkAccident,
  SuccessionPlan,
  WorkforceEvent,
  TerminationReason,
} from '@/lib/types';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const RAW = path.join(ROOT, 'data-sources/raw');
const OUT = path.join(ROOT, 'lib/data/generated');
const SEED = 42;

const THIS_YEAR = 2026;
const START_MONTH = '2023-01';
const END_MONTH = '2026-03';

function writeTsModule(filename: string, exportName: string, data: unknown): void {
  const body = `// AUTO-GENERATED by scripts/gen-data.ts — DO NOT EDIT\nexport const ${exportName} = ${JSON.stringify(data, null, 2)} as const;\n`;
  writeFileSync(path.join(OUT, filename), body, 'utf8');
}

function main(): void {
  console.log('🏗  HR Analytics data pipeline — start');
  mkdirSync(OUT, { recursive: true });

  // === 1. Parse real data ===
  const sp = parseStaffplan(path.join(RAW, 'Staffplan.xlsx'));
  const wf = parseWorkforceEvents(path.join(RAW, 'Nastupy_vystupy.xlsx'));
  const rec = parseRecruitment(path.join(RAW, 'recruitment_report.xlsx'));
  console.log(`   real data: ${sp.positions.length} positions, ${wf.events.length} wf events, ${rec.rows.length} recruitment rows`);

  // === 2. Build Position[] with heuristics ===
  const deptCountByRole = new Map<string, number>();
  for (const p of sp.positions) {
    const key = `${p.departmentId}:${p.roleFamily}`;
    deptCountByRole.set(key, (deptCountByRole.get(key) ?? 0) + 1);
  }
  const positions: Position[] = sp.positions.map((p) => {
    const grade = inferGrade({ title: p.title, hierCode: p.departmentId });
    const singletonInDept = (deptCountByRole.get(`${p.departmentId}:${p.roleFamily}`) ?? 0) <= 2;
    const criticalFlag = inferCriticalFlag({ grade, roleFamily: p.roleFamily, singletonInDept });
    return { ...p, grade, criticalFlag };
  });

  // === 3. Build Employee[] from workforce events ===
  const pseudo = createNamePseudonymizer(SEED);
  const termReasons = ['resignation', 'mutual_agreement', 'dismissal', 'probation_end'] as const;

  const matchPosition = (orgUnitName: string): Position => {
    const name = orgUnitName.toLowerCase();
    const byDept = positions.find((p) => name.includes(p.title.toLowerCase().split(' ')[0] ?? '__none__'));
    if (byDept) return byDept;
    const byRoleFamily = positions.find((p) => {
      const rf = p.roleFamily.toLowerCase();
      return name.includes(rf)
        || (rf === 'ops-driver' && name.includes('driver'))
        || (rf === 'ops-helper' && name.includes('helper'));
    });
    return byRoleFamily ?? positions[0]!;
  };

  const employees: Employee[] = [];
  for (const [osčpv, info] of wf.employees) {
    const rngG = seedrandom(`${SEED}:g:${osčpv}`);
    const rngTr = seedrandom(`${SEED}:tr:${osčpv}`);
    const rngBd = seedrandom(`${SEED}:bd:${osčpv}`);
    const g: Gender = rngG() < 0.75 ? 'male' : 'female';
    const names = pseudo.pseudonymize(osčpv, g);
    const position = matchPosition(info.orgUnitName);
    const termReason: TerminationReason | null = info.currentlyActive
      ? null
      : termReasons[Math.floor(rngTr() * termReasons.length)]!;
    const birthYear = 1965 + Math.floor(rngBd() * 40);
    employees.push({
      id: osčpv,
      firstName: names.firstName,
      lastName: names.lastName,
      gender: g,
      birthDate: `${birthYear}-06-15`,
      nationality: 'CZ',
      country: 'CZ',
      hireDate: info.firstSeenDate,
      terminationDate: info.currentlyActive ? null : info.lastSeenDate,
      terminationReason: termReason,
      positionId: position.id,
      divisionId: position.divisionId,
      departmentId: position.departmentId,
      orgUnitId: info.orgUnitCode,
      grade: position.grade,
      employmentType: info.employmentType,
      fte: position.actualFte > 0 ? 1 : 0.5,
      managerId: null,
      criticalPositionFlag: position.criticalFlag,
      talentPoolFlag: false,
      successorForPositionId: null,
    });
  }
  console.log(`   employees built: ${employees.length}`);

  // === 4. Mock facts ===
  const payroll: PayrollMonth[] = [];
  const absence: AbsenceRecord[] = [];
  const training: TrainingCompletion[] = [];
  const perf: PerformanceReview[] = [];

  for (const emp of employees) {
    payroll.push(...generatePayrollForEmployee(emp, { fromMonth: START_MONTH, toMonth: END_MONTH, seed: SEED }));
    for (let y = 2023; y <= THIS_YEAR; y++) {
      absence.push(...generateAbsenceForEmployee(emp, { year: y, seed: SEED }));
      training.push(...generateTrainingCompletions(emp, { year: y, seed: SEED }));
    }
    for (const cycle of ['2024', '2025']) {
      const activeInCycle =
        new Date(emp.hireDate).getFullYear() <= Number(cycle) &&
        (!emp.terminationDate || new Date(emp.terminationDate).getFullYear() >= Number(cycle));
      if (activeInCycle) perf.push(generatePerformanceReview(emp, { cycle, seed: SEED }));
    }
  }

  const activeEmployees = employees.filter((e) => !e.terminationDate);
  const enps: ENPSResponse[] = generateEnpsResponses(activeEmployees, {
    cycle: '2025-Q4',
    seed: SEED,
    participationRate: 0.7,
  });

  const divisionHc = new Map<string, number>();
  for (const e of activeEmployees) divisionHc.set(e.divisionId, (divisionHc.get(e.divisionId) ?? 0) + 1);
  const accidents: WorkAccident[] = [];
  for (const [divId, hc] of divisionHc) {
    for (let y = 2023; y <= THIS_YEAR; y++) {
      accidents.push(...generateAccidents({ divisionId: divId, year: y, headcount: hc, seed: SEED }));
    }
  }

  const successionPlans: SuccessionPlan[] = [];
  for (const p of positions.filter((p) => p.criticalFlag)) {
    const incumbent = employees.find((e) => e.positionId === p.id && !e.terminationDate) ?? null;
    const candidates = activeEmployees
      .filter((e) => e.grade === 'B3' || e.grade === 'B2')
      .slice(0, 5)
      .map((e) => ({ employeeId: e.id }));
    successionPlans.push(
      generateSuccessionPlan({
        positionId: p.id,
        incumbentEmployeeId: incumbent?.id ?? null,
        candidates,
        seed: SEED,
      }),
    );
  }

  // === 5. Workforce events re-export ===
  const wfEvents: WorkforceEvent[] = wf.events.map((e) => ({
    date: e.date,
    employeeId: e.employeeId,
    type: e.type,
    reason: undefined,
    voluntary: undefined,
  }));

  // === 6. Write outputs ===
  writeTsModule('employees.ts', 'EMPLOYEES', employees);
  writeTsModule('positions.ts', 'POSITIONS', positions);
  writeTsModule('departments.ts', 'DEPARTMENTS', sp.departments);
  writeTsModule('divisions.ts', 'DIVISIONS', sp.divisions);
  writeTsModule('payroll.ts', 'PAYROLL', payroll);
  writeTsModule('absence.ts', 'ABSENCE', absence);
  writeTsModule('training.ts', 'TRAINING', training);
  writeTsModule('performance.ts', 'PERFORMANCE', perf);
  writeTsModule('enps.ts', 'ENPS', enps);
  writeTsModule('accidents.ts', 'ACCIDENTS', accidents);
  writeTsModule('succession.ts', 'SUCCESSION', successionPlans);
  writeTsModule('workforce-events.ts', 'WORKFORCE_EVENTS', wfEvents);

  console.log('✅ Data pipeline complete.');
  console.log(`   📄 ${OUT}`);
}

main();
